require("nuggetnchill.plugins-setup")
require("nuggetnchill.core.options")
require("nuggetnchill.core.keymaps")
require("nuggetnchill.core.colorscheme")
require("nuggetnchill.plugins.comment")
require("nuggetnchill.plugins.nvim-tree")
require("nuggetnchill.plugins.lualine")
require("nuggetnchill.plugins.telescope")
