#!/bin/bash

options=(
	style=round
	width=10.0
	hidpi=off
	active_color="gradient(top_left=0xffffc640,bottom_right=0xffff6be7)"
	inactive_color="gradient(top_left=0xaa45c4c0,bottom_right=0xaaba3aa5)"
)

borders "${options[@]}"
